### ISSUE TITLE
need little help 

### ISSUE THREAD

**Issue by Veria70** [Nullspace-Colombia/unray-bridge#11]
Hi,
I want to create RL Based Driving Car System, i used  Cartpole BP and set everything but i think something was missed in my Implementation, 
how to define minus reward or using trace channel to Observation system??!!
I have RL based car and Goal actor in my scene, i used distance between car and goal actor and connected value to Observation function.
![Screenshot 2023-11-18 125304](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/ded5766b-a6aa-4531-a25c-325c256e2447)
![Screenshot 2023-11-18 125333](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/3aff8ca0-1810-4955-bbb3-60679e3e1dc0)
![Screenshot 2023-11-18 125344](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/918393c4-cf68-4726-9321-a7844fb13134)
![Screenshot 2023-11-18 125351](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/955d1c84-66b6-4664-9fff-4c69244598d8)
Thank You for your help
Best Regards.

**Comment by GDiaz16** [comment]
Hi @Veria70, we are going to review your code, but in any case we will publish a video making the example of a RL Driving Car System this week, based in what you have done, so you can understand what do you need to make your car to drive itself with Unray.

**Comment by Veria70** [comment]
Thank you so much, I building track for race and complete my Implementation (UE5 & Python) for RL System.
![Screenshot 2023-11-19 124501](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/fc1f7dd0-6ec2-4dfa-baa9-31470d8c9b68)
![Screenshot 2023-11-19 124519](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/0679209e-c914-4890-ba0a-64497e996365)
![Screenshot 2023-11-19 124529](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/1c9c7054-028a-46da-a9e3-01843588953a)
![Screenshot 2023-11-19 124537](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/5e5756f3-6e51-4017-9d23-83015018fcd3)
![Screenshot 2023-11-19 124547](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/c54a7e1c-e7a9-4c66-941e-09bf8c02aa23)
![Screenshot 2023-11-19 124556](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/1560e87a-d732-414f-ba8d-f044227624c1)
![Screenshot 2023-11-19 124603](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/e957d3d2-2b3e-4e2d-881d-42aae032cbc8)
![Screenshot 2023-11-19 124609](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/7dc0cf52-dd04-47dc-b80f-e2fb29471d20)
![Screenshot 2023-11-19 124635](https://github.com/Nullspace-Colombia/unray-bridge/assets/13269238/cabc1ed0-2904-4106-b9cb-da6bcd15efa4)

Python Config :

    obs_config = {
            "space": BridgeSpaces.Box(np.array([np.finfo(np.float32).min,0,0,0,0,0,0,0,0]),
            np.array([np.finfo(np.float32).max,
            np.finfo(np.float32).max,
            np.finfo(np.float32).max,
            np.finfo(np.float32).max,
            np.finfo(np.float32).max,
            np.finfo(np.float32).max,
            np.finfo(np.float32).max,
            np.finfo(np.float32).max,
            np.finfo(np.float32).max
            ])), 
            "description": "General coordinates of the cartpole"
        }

    act_config = {
            "space": BridgeSpaces.Box(np.array([-1,-1,0]),np.array([1,1,1])), #Throttle/Steering/Brake
            "description": "General coordinates of the cartpole"
    }
    
    
Best Regards.

**Comment by Veria70** [comment]
another Request : Give us Help to save model and load model 
Thanks.

**Comment by GDiaz16** [comment]
Hi Veria, we are still working in the video tutorial, in the meantime, this is the documentation on how to save a checkpoint with RLlib: https://docs.ray.io/en/latest/rllib/rllib-saving-and-loading-algos-and-policies.html#how-do-i-create-an-algorithm-checkpoint 

And this is how you restore the model checkpoint from your disk drive https://docs.ray.io/en/latest/rllib/rllib-saving-and-loading-algos-and-policies.html#how-do-i-restore-an-algorithm-from-a-checkpoint

**Comment by vahernandezmo** [comment]
Hi!
I wanted to check if you were able to use the trace channel in the observation system.

**Comment by Veria70** [comment]
Hi @vahernandezmo @GDiaz16 
Do you Publish Tutorial Video About RL Car Racing or Something Similar?
I Really Need Practical Tutorial as Document Or Video.
Thank You Very Much.
Best Regards.

**Comment by Veria70** [comment]
Hi @GDiaz16 Thank You Very Much, I'm waiting for your tutorial.

**Comment by GDiaz16** [comment]
Hi @Veria70, this is an update of the tutorial we are working on, the car is already training to complete the track, let me know if you want something else to be shown in the tutorial.
https://github.com/Nullspace-Colombia/unray-bridge/assets/16580160/85bbb0a5-75a2-4da3-be9f-f3ac76437bc1

**Comment by Veria70** [comment]
Hi @GDiaz16 It is wonderful, I would be grateful if the method of model inference is included in your tutorial. Thank you for your hard work.

**Comment by GDiaz16** [comment]
Hi @Veria70, just to let you know that the tutorial you requested has just been uploaded, you can go and check it out! Sorry for the delay tho. https://youtu.be/O3azZNGmeGo?si=24KDS4sBS6hqF3VU

**Comment by Veria70** [comment]
Thank you so much @GDiaz16
