### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by f00d4tehg0dz** [Nullspace-Colombia/unray-bridge#12]
Hey Team,

I'm running into issues trying out both examples you have provided. 

**Issue**

When running in command prompt `python parallel_multiagentArena.py`
I receive this error: 
`OverflowError: int too big to convert`
And when running in command prompt `python main_cartpole.py` 
I receive this error 
`[ CONNECTION ] connecting to localhost port 10010`
`Trying to connect...`
`Trying to connect...`
`Trying to connect...`
`Trying to connect...`
`Connection Timeout!`

What's interesting is when running in command prompt `netstat -a | findstr :10011` I do get a response from UE5.3
 ` TCP    0.0.0.0:10011          www:0                  LISTENING`
 
**Steps to reproduce**

Create a new VirtualEnv with Anaconda 3. 

1. Use Python 3.10.x (have tried 3.8.x as well)
2. `git clone https://github.com/Nullspace-Colombia/unray-bridge.git`
`cd unray-bridge`
`pip install -r requirements.txt`
`pip install tensorflow`
3. In Anaconda 3 select your new Virtual Environment and click the green play button and select Open Terminal
4. Enable the UE 5.3 plugin Remote Control API
5. Restart UE 5.3
6. Inside Project Settings, select Plugins - Remote Control
7. Under Remote Control WebSocket Server Port, enter in `10011`
8. Select map MultiAgentArena
9. Press the Green Play button in the UE 5.3 Editor
10. In your Terminal (command prompt)
11. Run in command prompt `python main_multiagentArena.py`
12. Wait for error

**Hardware**

- Intel Core i9 12900KF
- ASUS TUF GAMING Z690-PLUS WIFI D4
- Corsair 32 GB DDR4 @3200mhz
- Samsung SSD 980 PRO 2TB
- NVIDIA GeForce RTX 3090

**Comment by f00d4tehg0dz** [comment]
Disregard. My initial problem was I was unable to connect via localhost from your Python script, so I assumed improperly that I needed to use the remote control plugin. 

Closing this as I'm good now.

**Comment by GDiaz16** [comment]
@f00d4tehg0dz Great that you solved the issue!
